// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCovYNYUdJHZhqdF3RagI39GoWh2TQfew8',
    appId: '1:944035348932:web:b5e1c09e5e356ecf8d2491',
    messagingSenderId: '944035348932',
    projectId: 'outspot-dfae2',
    authDomain: 'outspot-dfae2.firebaseapp.com',
    storageBucket: 'outspot-dfae2.firebasestorage.app',
    measurementId: 'G-73QL4LXHX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtPLZKeN4YbSrUzLRqwGkiyHl-0rk8wVU',
    appId: '1:944035348932:android:31949db75a5a8c238d2491',
    messagingSenderId: '944035348932',
    projectId: 'outspot-dfae2',
    storageBucket: 'outspot-dfae2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNB-SP77wSlgCGJhSEQmrWCu7AVj8GAO8',
    appId: '1:944035348932:ios:c4f583f23fe812028d2491',
    messagingSenderId: '944035348932',
    projectId: 'outspot-dfae2',
    storageBucket: 'outspot-dfae2.firebasestorage.app',
    androidClientId: '944035348932-8dnmauasfeuh2e1lg1pnk7ufm17b25a9.apps.googleusercontent.com',
    iosClientId: '944035348932-dl3o1o7rqoq3338rluibm0d8lq588bdh.apps.googleusercontent.com',
    iosBundleId: 'com.outspot.app.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNB-SP77wSlgCGJhSEQmrWCu7AVj8GAO8',
    appId: '1:944035348932:ios:200d267b711f5de98d2491',
    messagingSenderId: '944035348932',
    projectId: 'outspot-dfae2',
    storageBucket: 'outspot-dfae2.firebasestorage.app',
    iosBundleId: 'com.example.outspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCovYNYUdJHZhqdF3RagI39GoWh2TQfew8',
    appId: '1:944035348932:web:adf9dff059fc74a28d2491',
    messagingSenderId: '944035348932',
    projectId: 'outspot-dfae2',
    authDomain: 'outspot-dfae2.firebaseapp.com',
    storageBucket: 'outspot-dfae2.firebasestorage.app',
    measurementId: 'G-3PFXMPY3PL',
  );

}